import DesktopSidebar, { sidebarItems } from "@/announcement/resuable-components/sidebar";
import TopBar, { menuItems } from "@/announcement/resuable-components/topbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GoSchool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
       <TopBar isUser={true}/>
       <div style={{gridTemplateColumns: 'repeat(2, 1fr)'}} className="px-[40px] grid gap-5 mt-[120px]">
        <DesktopSidebar
        navlinks={sidebarItems}
      />
          {children}
      </div>
        </body>
    </html>
  );
}
