export const formInputs = [
  {
    id: 1,
    title: 'First Name*',
    type: 'text',
    name: 'firstName',
  },
  {
    id: 2,
    title: 'Last Name*',
    type: 'text',
    name: 'lastName',
  },
  {
    id: 3,
    title: 'Phone Number*',
    type: 'phonenumber',
    name: 'phoneNumber',
  },
  {
    id: 4,
    title: 'Work Email*',
    type: 'email',
    name: 'email',
  },
  {
    id: 5,
    title: 'Company Name*',
    type: 'text',
    name: 'companyName',
  },
  {
    id: 6,
    title: 'What is your position/title?This question is required. *',
    type: 'text',
    name: 'position',
  },
]

export const selectData = [
  {
    id: 1,
    question: "Please select your ideal lead's management level*",
    options: [
      'owner',
      'partner',
      'cxo',
      'vice-president-vp',
      'director',
      'manager',
      'senior',
      'entry',
      'training',
      'unpaid',
    ],
  },
  {
    id: 2,
    question: "Please select your ideal lead's role*",
    options: [
      'customer service',
      'design',
      'education',
      'engineering',
      'finance',
      'health',
      'human resources',
      'legal',
      'marketing',
      'media',
      'operations',
      'public relations',
      'real estate',
      'sales',
      'trades',
    ],
  },
  {
    id: 3,
    question: "Please select your ideal lead's company size*",
    options: [
      '1-10',
      '11-50',
      '51-200',
      '201-500',
      '501-1000',
      '1001-5000',
      '5001-10000',
      '10001+',
    ],
  },
  {
    id: 4,
    question: "Please select your ideal prospect's industry*",
    options: [
      'accounting',
      'airlines/aviation',
      'alternative dispute resolution',
      'alternative medicine',
      'animation',
      'apparel & fashion',
      'architecture & planning',
      'arts and crafts',
      'automotive',
      'aviation & aerospace',
      'banking',
      'biotechnology',
      'broadcast media',
      'building materials',
      'business supplies and equipment',
      'capital markets',
      'chemicals',
      'civic & social organization',
      'civil engineering',
      'commercial real estate',
      'computer & network security',
      'computer games',
      'computer hardware',
      'computer networking',
      'computer software',
      'construction',
      'consumer electronics',
      'consumer goods',
      'consumer services',
      'cosmetics',
      'dairy',
      'defense & space',
      'design',
      'e-learning',
      'education management',
      'electrical/electronic manufacturing',
      'entertainment',
      'environmental services',
      'events services',
      'executive office',
      'facilities services',
      'farming',
      'financial services',
      'fine art',
      'fishery',
      'food & beverages',
      'food production',
      'fund-raising',
      'furniture',
      'gambling & casinos',
      'glass, ceramics, & concrete',
      'government administration',
      'government relations',
      'graphic design',
      'health, wellness and fitness',
      'higher education',
      'hospital & health care',
      'hospitality',
      'human resources',
      'import and export',
      'individual & family services',
      'industrial automation',
      'information services',
      'information technology and services',
      'insurance',
      'international affairs',
      'international trade and development',
      'internet',
      'investment banking',
      'investment management',
      'judiciary',
      'law enforcement',
      'law practice',
      'legal services',
      'legislative office',
      'leisure, travel, & tourism',
      'libraries',
      'logistics and supply chain',
      'luxury goods & jewelry',
      'machinery',
      'management consulting',
      'maritime',
      'market research',
      'marketing and advertising',
      'mechanical or industrial engineering',
      'media production',
      'medical devices',
      'medical practice',
      'mental health care',
      'military',
      'mining & metals',
      'motion pictures and film',
      'museums and institutions',
      'music',
      'nanotechnology',
      'newspapers',
      'non-profit organization management',
      'oil & energy',
      'online media',
      'outsourcing/offshoring',
      'package/freight delivery',
      'packaging and containers',
      'paper & forest products',
      'performing arts',
      'pharmaceuticals',
      'philanthropy',
      'photography',
      'plastics',
      'political organization',
      'primary/secondary education',
      'printing',
      'professional training & coaching',
      'program development',
      'public policy',
      'public relations and communications',
      'public safety',
      'publishing',
      'railroad manufacture',
      'ranching',
      'real estate',
      'recreational facilities and services',
      'religious institutions',
      'renewables & environment',
      'research',
      'restaurants',
      'retail',
      'security and investigations',
      'semiconductors',
      'shipbuilding',
      'sporting goods',
      'sports',
      'staffing and recruiting',
      'supermarkets',
      'telecommunications',
      'textiles',
      'think tanks',
      'tobacco',
      'translation and localization',
      'transportation/trucking/railroad',
      'utilities',
      'venture capital & private equity',
      'veterinary',
      'warehousing',
      'wholesale',
      'wine and spirits',
      'wireless',
      'writing and editing',
    ],
  },
]
